#!/bin/bash

if [[ ! -f "./main" ]]; then
    cd ../ ; make asgn_01

    if (( $? != 0 )); then
        exit 1
    fi
fi

cat ./tests/${1}.in | ./main

echo "---------- expected output ----------"

cat ./tests/${1}.out

echo ""
